import csv
import os

leads = [
    # --- USA LEADS (1 - 25) ---
    {
        "id": 1,
        "business_name": "Royal Dates & Nuts Market",
        "country": "USA",
        "city": "Paterson, NJ",
        "maps_profile": "https://maps.google.com/?q=Royal+Dates+Nuts+Paterson+NJ",
        "website_status": "No website (Google Maps & Instagram only)",
        "social": "Instagram: @royaldates_paterson / FB: Royal Dates Paterson",
        "contact": "+1 973-555-0182 | sales@royaldatespaterson.com",
        "owner": "Tariq Mansour (Owner)",
        "why_need_website": "High foot traffic for Medjool & Ajwa dates, relies on phone orders. Lacks modern e-commerce checkout & subscriptions.",
        "quality": "High"
    },
    {
        "id": 2,
        "business_name": "Al-Basha Gourmet Nuts & Spices",
        "country": "USA",
        "city": "Dearborn, MI",
        "maps_profile": "https://maps.google.com/?q=Al+Basha+Gourmet+Nuts+Dearborn+MI",
        "website_status": "Outdated 1-page site (No online ordering)",
        "social": "FB: AlBashaDearborn / IG: @albasha_nuts",
        "contact": "+1 313-582-9900 | info@albashanuts.com",
        "owner": "Hassan Al-Basha (Managing Partner)",
        "why_need_website": "Roasts custom nut blends daily. Customers want nationwide shipping & online order management.",
        "quality": "High"
    },
    {
        "id": 3,
        "business_name": "Cedar Market Dry Fruits & Sweets",
        "country": "USA",
        "city": "Bay Ridge, Brooklyn, NY",
        "maps_profile": "https://maps.google.com/?q=Cedar+Market+Dry+Fruits+Brooklyn+NY",
        "website_status": "No website (Google Maps profile only)",
        "social": "FB: CedarMarketBrooklyn",
        "contact": "+1 718-491-2200 | contact@cedarmarketny.com",
        "owner": "Samir Haddad (Store Manager)",
        "why_need_website": "Popular local shop for organic figs, pistachios, and dried apricots; missing out on NYC online gourmet market.",
        "quality": "High"
    },
    {
        "id": 4,
        "business_name": "Sultan Dry Fruits & Gourmet Baskets",
        "country": "USA",
        "city": "Chicago, IL",
        "maps_profile": "https://maps.google.com/?q=Sultan+Dry+Fruits+Chicago+IL",
        "website_status": "Expired domain / Social ordering only",
        "social": "IG: @sultan_dryfruits_chi",
        "contact": "+1 312-600-4411 | sultanfoodschi@gmail.com",
        "owner": "Nabil Sultan (Owner)",
        "why_need_website": "Sells corporate gift boxes during holidays via DMs. Needs automated custom box builder & payment gateway.",
        "quality": "High"
    },
    {
        "id": 5,
        "business_name": "California Sun Dried Fruits & Nuts",
        "country": "USA",
        "city": "Fresno, CA",
        "maps_profile": "https://maps.google.com/?q=California+Sun+Dried+Fruits+Fresno+CA",
        "website_status": "Outdated non-responsive website (Built 2012)",
        "social": "FB: SunDriedFruitsFresno",
        "contact": "+1 559-224-8833 | sunfruitfresno@yahoo.com",
        "owner": "Robert Garza (Founder)",
        "why_need_website": "Direct farm grower offering raisins, almonds & walnuts. Mobile UX broken, no modern cart experience.",
        "quality": "High"
    },
    {
        "id": 6,
        "business_name": "Ziyad Dates & Roastery",
        "country": "USA",
        "city": "Bridgeview, IL",
        "maps_profile": "https://maps.google.com/?q=Ziyad+Dates+Roastery+Bridgeview+IL",
        "website_status": "No e-commerce (Catalog view only)",
        "social": "IG: @ziyad_roastery / FB: ZiyadRoastery",
        "contact": "+1 708-430-1100 | orders@ziyadroastery.com",
        "owner": "Karim Ziyad (General Manager)",
        "why_need_website": "High volume wholesale & retail roasted nuts shop. Customers repeatedly ask for DTC e-commerce cart.",
        "quality": "High"
    },
    {
        "id": 7,
        "business_name": "Pistachio Palace & Dried Fruit Boutique",
        "country": "USA",
        "city": "Glendale, CA",
        "maps_profile": "https://maps.google.com/?q=Pistachio+Palace+Glendale+CA",
        "website_status": "No website (Yelp & Google Maps profile)",
        "social": "IG: @pistachiopalace_glendale",
        "contact": "+1 818-243-7711 | pistachiopalace@outlook.com",
        "owner": "Armen Sarkissian (Co-Owner)",
        "why_need_website": "4.8-star rated specialty Persian nut shop. Lacks online showcase for premium gift boxes.",
        "quality": "High"
    },
    {
        "id": 8,
        "business_name": "Sahara Dates & Gourmet Snacks",
        "country": "USA",
        "city": "Houston, TX",
        "maps_profile": "https://maps.google.com/?q=Sahara+Dates+Gourmet+Houston+TX",
        "website_status": "No website (WhatsApp ordering only)",
        "social": "FB: SaharaDatesHouston",
        "contact": "+1 713-789-5500 | saharadateshouston@gmail.com",
        "owner": "Faris Al-Ameri (Owner)",
        "why_need_website": "Large inventory of stuffed dates & prunes. Currently taking manual orders on WhatsApp.",
        "quality": "High"
    },
    {
        "id": 9,
        "business_name": "Golden Nut House & Organic Fruits",
        "country": "USA",
        "city": "San Jose, CA",
        "maps_profile": "https://maps.google.com/?q=Golden+Nut+House+San+Jose+CA",
        "website_status": "Broken shopping cart script",
        "social": "IG: @goldennuthouse_sj",
        "contact": "+1 408-984-3322 | goldennuthouse@gmail.com",
        "owner": "David Chen (Store Manager)",
        "why_need_website": "Prime Silicon Valley location, high demand for bulk organic snack boxes, current site checkout throws errors.",
        "quality": "High"
    },
    {
        "id": 10,
        "business_name": "Al-Khair Organic Dates & Seeds",
        "country": "USA",
        "city": "Anaheim, CA",
        "maps_profile": "https://maps.google.com/?q=Al+Khair+Organic+Dates+Anaheim+CA",
        "website_status": "No website (Instagram bio link broken)",
        "social": "IG: @alkhairdates_anaheim",
        "contact": "+1 714-635-4422 | alkhairdates@gmail.com",
        "owner": "Mo Al-Khair (Owner)",
        "why_need_website": "Specialized organic date producer in Little Arabia district. Needs professional direct-to-consumer store.",
        "quality": "High"
    },
    {
        "id": 11,
        "business_name": "Valley Orchard Dried Fruit Co.",
        "country": "USA",
        "city": "Bakersfield, CA",
        "maps_profile": "https://maps.google.com/?q=Valley+Orchard+Dried+Fruit+Bakersfield+CA",
        "website_status": "Outdated WIX free tier site",
        "social": "FB: ValleyOrchardFruits",
        "contact": "+1 661-397-1234 | valleyorchardca@gmail.com",
        "owner": "Sarah Jenkins (Marketing Lead)",
        "why_need_website": "Local orchard selling dried peaches, figs & pecans. WIX ad banner ruins premium brand perception.",
        "quality": "High"
    },
    {
        "id": 12,
        "business_name": "Midwest Nut & Candy Emporium",
        "country": "USA",
        "city": "Columbus, OH",
        "maps_profile": "https://maps.google.com/?q=Midwest+Nut+Candy+Emporium+Columbus+OH",
        "website_status": "No e-commerce (PDF catalog only)",
        "social": "FB: MidwestNutEmporium",
        "contact": "+1 614-488-9900 | info@midwestnutemporium.com",
        "owner": "Greg Miller (Owner)",
        "why_need_website": "Historic local nut roaster. Requires real-time online inventory and cart for retail customers.",
        "quality": "Medium"
    },
    {
        "id": 13,
        "business_name": "Al-Arabiya Nuts & Roasting House",
        "country": "USA",
        "city": "Dallas, TX",
        "maps_profile": "https://maps.google.com/?q=Al+Arabiya+Nuts+Dallas+TX",
        "website_status": "No website (Google Business Profile)",
        "social": "IG: @alarabiya_nuts_dallas",
        "contact": "+1 214-575-8844 | alarabiyanutsdfw@gmail.com",
        "owner": "Youssef Nader (Owner)",
        "why_need_website": "High Yelp reviews for smoked cashews & pumpkin seeds. No digital channel for bulk online orders.",
        "quality": "High"
    },
    {
        "id": 14,
        "business_name": "Oasis Date Gardens Retail Store",
        "country": "USA",
        "city": "Thermal, CA",
        "maps_profile": "https://maps.google.com/?q=Oasis+Date+Gardens+Thermal+CA",
        "website_status": "Outdated legacy site",
        "social": "FB: OasisDateGardens",
        "contact": "+1 760-399-5151 | retail@oasisdate.com",
        "owner": "Elena Ramirez (Store Operations)",
        "why_need_website": "Historic date farm. Legacy site is clunky on mobile devices, missing gift-box customization.",
        "quality": "High"
    },
    {
        "id": 15,
        "business_name": "Desert Gold Dates & Organic Nuts",
        "country": "USA",
        "city": "Phoenix, AZ",
        "maps_profile": "https://maps.google.com/?q=Desert+Gold+Dates+Phoenix+AZ",
        "website_status": "No website (FB page only)",
        "social": "FB: DesertGoldDatesAZ",
        "contact": "+1 602-276-8800 | desertgolddates@gmail.com",
        "owner": "Marcus Vance (Co-Owner)",
        "why_need_website": "Sells high grade Arizona dates & pecans. Relying on phone orders and farmers market stalls.",
        "quality": "Medium"
    },
    {
        "id": 16,
        "business_name": "Mediterranean Nut & Spice Market",
        "country": "USA",
        "city": "Tampa, FL",
        "maps_profile": "https://maps.google.com/?q=Mediterranean+Nut+Spice+Tampa+FL",
        "website_status": "No website (Google Maps profile)",
        "social": "IG: @mednutmarket_tampa",
        "contact": "+1 813-931-7788 | mednutmarket@gmail.com",
        "owner": "Khaled El-Sayed (Owner)",
        "why_need_website": "Specialized imported Turkish & Greek nuts. No web presence to capture Florida foodies.",
        "quality": "High"
    },
    {
        "id": 17,
        "business_name": "Sunland Gourmet Dried Fruit & Snacks",
        "country": "USA",
        "city": "Sacramento, CA",
        "maps_profile": "https://maps.google.com/?q=Sunland+Gourmet+Dried+Fruit+Sacramento+CA",
        "website_status": "Basic Weebly site (No SSL / No checkout)",
        "social": "FB: SunlandSnacksSac",
        "contact": "+1 916-442-3311 | sunlandsnacks@yahoo.com",
        "owner": "Jessica Thorne (Owner)",
        "why_need_website": "Insecure site turns off online buyers. Needs modern SSL-enabled Next.js e-commerce storefront.",
        "quality": "High"
    },
    {
        "id": 18,
        "business_name": "Jerusalem Nut House",
        "country": "USA",
        "city": "Jersey City, NJ",
        "maps_profile": "https://maps.google.com/?q=Jerusalem+Nut+House+Jersey+City+NJ",
        "website_status": "No website (Google Maps & phone only)",
        "social": "FB: JerusalemNutHouseJC",
        "contact": "+1 201-434-9922 | jerusalemnuthouse@gmail.com",
        "owner": "Ibrahim Qasim (Owner)",
        "why_need_website": "Famous for freshly roasted watermelon seeds, pine nuts & dates. Missing out on regional shipping.",
        "quality": "High"
    },
    {
        "id": 19,
        "business_name": "Cascade Organic Dried Berry & Nut Co.",
        "country": "USA",
        "city": "Portland, OR",
        "maps_profile": "https://maps.google.com/?q=Cascade+Organic+Dried+Berry+Portland+OR",
        "website_status": "Outdated WordPress site with broken plugins",
        "social": "IG: @cascade_organics_pdx",
        "contact": "+1 503-233-6644 | info@cascadeorganics.net",
        "owner": "Chloe Bennett (Founder)",
        "why_need_website": "Artisanal dried blueberries, hazelnuts & trail mixes. Current site crashes at checkout.",
        "quality": "High"
    },
    {
        "id": 20,
        "business_name": "Baja Roasters & Nut Traders",
        "country": "USA",
        "city": "San Diego, CA",
        "maps_profile": "https://maps.google.com/?q=Baja+Roasters+Nut+Traders+San+Diego+CA",
        "website_status": "No website (Instagram store link missing)",
        "social": "IG: @bajaroasters_sd",
        "contact": "+1 619-280-5511 | bajaroasters@gmail.com",
        "owner": "Mateo Gutierrez (Manager)",
        "why_need_website": "High volume of gourmet spicy nuts and trail mixes sold locally. Needs online store for expansion.",
        "quality": "Medium"
    },
    {
        "id": 21,
        "business_name": "Atlas Date & Dry Fruit Traders",
        "country": "USA",
        "city": "Minneapolis, MN",
        "maps_profile": "https://maps.google.com/?q=Atlas+Date+Traders+Minneapolis+MN",
        "website_status": "No website (Phone orders only)",
        "social": "FB: AtlasDatesMN",
        "contact": "+1 612-871-3300 | atlasdatesmn@gmail.com",
        "owner": "Omar Farah (Owner)",
        "why_need_website": "Supplies premium North African dates & walnuts across Twin Cities. Needs e-commerce catalog.",
        "quality": "High"
    },
    {
        "id": 22,
        "business_name": "Golden Gate Dried Fruit & Gift Shop",
        "country": "USA",
        "city": "San Francisco, CA",
        "maps_profile": "https://maps.google.com/?q=Golden+Gate+Dried+Fruit+San+Francisco+CA",
        "website_status": "Static page without cart",
        "social": "IG: @goldengatefruit_sf",
        "contact": "+1 415-982-1188 | sales@goldengatefruit.com",
        "owner": "Lillian Wong (Co-Owner)",
        "why_need_website": "Tourist-heavy location selling dried mangoes & nuts. Wants automated global & national delivery site.",
        "quality": "High"
    },
    {
        "id": 23,
        "business_name": "Al-Mustafa Sweets & Dry Fruits",
        "country": "USA",
        "city": "Philadelphia, PA",
        "maps_profile": "https://maps.google.com/?q=Al+Mustafa+Dry+Fruits+Philadelphia+PA",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: AlMustafaPhilly",
        "contact": "+1 215-724-4400 | almustafaphilly@gmail.com",
        "owner": "Mustafa Ali (Owner)",
        "why_need_website": "Sells high-grade almonds, cashews & dates. No online menu or order placement.",
        "quality": "Medium"
    },
    {
        "id": 24,
        "business_name": "Peanut & Nut Emporium",
        "country": "USA",
        "city": "Atlanta, GA",
        "maps_profile": "https://maps.google.com/?q=Peanut+Nut+Emporium+Atlanta+GA",
        "website_status": "Outdated Square site (Limited inventory display)",
        "social": "IG: @atlanta_nut_emporium",
        "contact": "+1 404-523-7799 | contact@atlnutemporium.com",
        "owner": "Charles Dupree (Owner)",
        "why_need_website": "Southern pecan & roasted nut specialist. Square site lacks bundle customization and luxury design.",
        "quality": "High"
    },
    {
        "id": 25,
        "business_name": "Palmyra Date Co.",
        "country": "USA",
        "city": "Allentown, PA",
        "maps_profile": "https://maps.google.com/?q=Palmyra+Date+Co+Allentown+PA",
        "website_status": "No website (WhatsApp DM sales only)",
        "social": "IG: @palmyradates_pa",
        "contact": "+1 610-432-1155 | palmyradates@gmail.com",
        "owner": "Samer Kabbani (Owner)",
        "why_need_website": "Imports premium organic Syrian & Jordan dates. Manually billing via PayPal invoices, needs streamlined storefront.",
        "quality": "High"
    },

    # --- CANADA LEADS (26 - 40) ---
    {
        "id": 26,
        "business_name": "Al-Yasmeen Nuts & Roastery",
        "country": "Canada",
        "city": "Mississauga, ON",
        "maps_profile": "https://maps.google.com/?q=Al+Yasmeen+Nuts+Mississauga+ON",
        "website_status": "No website (Google Maps & IG page only)",
        "social": "IG: @alyasmeennuts_sauga",
        "contact": "+1 905-270-8880 | alyasmeennuts@gmail.com",
        "owner": "Fadi Al-Yasmeen (Owner)",
        "why_need_website": "Top-rated roastery in GTA. Customers constantly request online shipping across Canada.",
        "quality": "High"
    },
    {
        "id": 27,
        "business_name": "Montreal Nut & Dry Fruit House",
        "country": "Canada",
        "city": "Montreal, QC",
        "maps_profile": "https://maps.google.com/?q=Montreal+Nut+Dry+Fruit+Montreal+QC",
        "website_status": "Outdated 1-page site (French only, no cart)",
        "social": "FB: MontrealNutHouse",
        "contact": "+1 514-388-5522 | info@montrealnuthouse.ca",
        "owner": "Jacques Tremblay (Manager)",
        "why_need_website": "Bilingual market needs modern English/French luxury storefront with full cart & payment system.",
        "quality": "High"
    },
    {
        "id": 28,
        "business_name": "Balkh Dry Fruit & Date Traders",
        "country": "Canada",
        "city": "Toronto, ON",
        "maps_profile": "https://maps.google.com/?q=Balkh+Dry+Fruit+Toronto+ON",
        "website_status": "No website (Google Maps listing)",
        "social": "FB: BalkhDryFruitTO",
        "contact": "+1 416-751-9933 | balkhdryfruit@gmail.com",
        "owner": "Ahmad Balkhi (Owner)",
        "why_need_website": "Imports premium raisins, pine nuts & mulberries. Operates offline only.",
        "quality": "High"
    },
    {
        "id": 29,
        "business_name": "Pacific Nut & Dried Fruit Co.",
        "country": "Canada",
        "city": "Vancouver, BC",
        "maps_profile": "https://maps.google.com/?q=Pacific+Nut+Dried+Fruit+Vancouver+BC",
        "website_status": "Broken ecommerce checkout script",
        "social": "IG: @pacificnut_van",
        "contact": "+1 604-255-4411 | sales@pacificnut.ca",
        "owner": "Gordon Liu (Co-Founder)",
        "why_need_website": "Supplies Vancouver vegan & health community. Current WordPress checkout fails on mobile.",
        "quality": "High"
    },
    {
        "id": 30,
        "business_name": "Al-Arz Date & Nut House",
        "country": "Canada",
        "city": "Ottawa, ON",
        "maps_profile": "https://maps.google.com/?q=Al+Arz+Date+Nut+Ottawa+ON",
        "website_status": "No website (Facebook catalog only)",
        "social": "FB: AlArzNutHouseOttawa",
        "contact": "+1 613-744-6633 | alarznuthouse@gmail.com",
        "owner": "Rami El-Khoury (Manager)",
        "why_need_website": "High demand for Eid & holiday date boxes in Ottawa. Needs dedicated order portal.",
        "quality": "High"
    },
    {
        "id": 31,
        "business_name": "Calgary Date & Snack Market",
        "country": "Canada",
        "city": "Calgary, AB",
        "maps_profile": "https://maps.google.com/?q=Calgary+Date+Snack+Calgary+AB",
        "website_status": "No website (Google Maps profile)",
        "social": "IG: @calgarydatesnacks",
        "contact": "+1 403-248-1199 | calgarydates@gmail.com",
        "owner": "Tariq Mansoor (Owner)",
        "why_need_website": "Specialty supplier of stuffed Medjool dates & roasted almonds in Alberta.",
        "quality": "Medium"
    },
    {
        "id": 32,
        "business_name": "Cedar Dates & Organic Groceries",
        "country": "Canada",
        "city": "Edmonton, AB",
        "maps_profile": "https://maps.google.com/?q=Cedar+Dates+Edmonton+AB",
        "website_status": "Outdated WIX site without payment gateway",
        "social": "FB: CedarDatesEdmonton",
        "contact": "+1 780-469-8877 | info@cedardates.ca",
        "owner": "Bilal Kassam (Co-Owner)",
        "why_need_website": "WIX site has no payment integration, requiring interac e-transfers manually.",
        "quality": "High"
    },
    {
        "id": 33,
        "business_name": "Syrian Roastery & Gourmet Dry Fruits",
        "country": "Canada",
        "city": "Scarborough, ON",
        "maps_profile": "https://maps.google.com/?q=Syrian+Roastery+Scarborough+ON",
        "website_status": "No website (Instagram orders only)",
        "social": "IG: @syrianroastery_scarborough",
        "contact": "+1 416-291-7700 | syrianroastery@outlook.com",
        "owner": "Wael Al-Dimashqi (Owner)",
        "why_need_website": "Highly viral Instagram roastery. Needs automated e-commerce for shipping across Ontario.",
        "quality": "High"
    },
    {
        "id": 34,
        "business_name": "Fraser Valley Dried Fruit & Berry Barn",
        "country": "Canada",
        "city": "Abbotsford, BC",
        "maps_profile": "https://maps.google.com/?q=Fraser+Valley+Dried+Fruit+Abbotsford+BC",
        "website_status": "Static HTML page built in 2010",
        "social": "FB: FraserValleyDriedFruits",
        "contact": "+1 604-853-2211 | fvdriedfruits@telus.net",
        "owner": "Hannah Wiens (Owner)",
        "why_need_website": "Farm store selling dried cranberries, blueberries & hazelnuts. Mobile user experience non-existent.",
        "quality": "High"
    },
    {
        "id": 35,
        "business_name": "Al-Zahra Gourmet Dates & Sweets",
        "country": "Canada",
        "city": "Windsor, ON",
        "maps_profile": "https://maps.google.com/?q=Al+Zahra+Gourmet+Dates+Windsor+ON",
        "website_status": "No website (Google Business Profile)",
        "social": "FB: AlZahraWindsor",
        "contact": "+1 519-977-3344 | alzahrawindsor@gmail.com",
        "owner": "Fatima Zahra (Owner)",
        "why_need_website": "Cross-border popularity with Detroit buyers. Needs e-commerce store with CAD/USD currency toggle.",
        "quality": "High"
    },
    {
        "id": 36,
        "business_name": "Royal Nut & Spice Traders",
        "country": "Canada",
        "city": "Hamilton, ON",
        "maps_profile": "https://maps.google.com/?q=Royal+Nut+Spice+Hamilton+ON",
        "website_status": "Outdated site with broken image links",
        "social": "IG: @royalnuthamilton",
        "contact": "+1 905-528-9911 | royalnuthamilton@gmail.com",
        "owner": "Suresh Patel (Owner)",
        "why_need_website": "Prominent nut & dried fruit supplier in Hamilton market. Outdated site repels younger buyers.",
        "quality": "Medium"
    },
    {
        "id": 37,
        "business_name": "Kabul Dry Fruit House",
        "country": "Canada",
        "city": "Burnaby, BC",
        "maps_profile": "https://maps.google.com/?q=Kabul+Dry+Fruit+Burnaby+BC",
        "website_status": "No website (Phone orders only)",
        "social": "FB: KabulDryFruitBurnaby",
        "contact": "+1 604-420-5566 | kabuldryfruitbc@gmail.com",
        "owner": "Habib Ahmadi (Owner)",
        "why_need_website": "Imports premium Afghan figs, almonds & pistachios. Needs modern catalog website.",
        "quality": "High"
    },
    {
        "id": 38,
        "business_name": "Maple Leaf Nut & Snack Co.",
        "country": "Canada",
        "city": "Kitchener, ON",
        "maps_profile": "https://maps.google.com/?q=Maple+Leaf+Nut+Snack+Kitchener+ON",
        "website_status": "No website (Google Maps profile)",
        "social": "IG: @mapleleafnuts_kw",
        "contact": "+1 519-743-8822 | mapleleafnuts@gmail.com",
        "owner": "David Miller (Co-Founder)",
        "why_need_website": "Local roasted nuts & maple-coated pecans supplier. Lacks online shop.",
        "quality": "Medium"
    },
    {
        "id": 39,
        "business_name": "Golden Palm Dates & Spices",
        "country": "Canada",
        "city": "Laval, QC",
        "maps_profile": "https://maps.google.com/?q=Golden+Palm+Dates+Laval+QC",
        "website_status": "No website (Instagram DM ordering)",
        "social": "IG: @goldenpalmdates_qc",
        "contact": "+1 450-681-4477 | goldenpalmdates@gmail.com",
        "owner": "Karim Bennani (Owner)",
        "why_need_website": "High-end date boutique in Greater Montreal area taking orders via DMs.",
        "quality": "High"
    },
    {
        "id": 40,
        "business_name": "Atlantic Dried Fruit & Nut Boutique",
        "country": "Canada",
        "city": "Halifax, NS",
        "maps_profile": "https://maps.google.com/?q=Atlantic+Dried+Fruit+Halifax+NS",
        "website_status": "Under construction for over 1 year",
        "social": "FB: AtlanticDriedFruitHalifax",
        "contact": "+1 902-429-1133 | atlanticdriedfruit@gmail.com",
        "owner": "Sean MacLeod (Owner)",
        "why_need_website": "Only specialty dried fruit shop in Halifax. Site stuck 'under construction', losing customers.",
        "quality": "High"
    },

    # --- UK LEADS (41 - 60) ---
    {
        "id": 41,
        "business_name": "Damascus Nut House & Roastery",
        "country": "UK",
        "city": "Edgware Road, London",
        "maps_profile": "https://maps.google.com/?q=Damascus+Nut+House+Edgware+Road+London",
        "website_status": "No website (Google Maps & IG only)",
        "social": "IG: @damascusnuthouse_london",
        "contact": "+44 20 7723 4488 | info@damascusnuthouse.co.uk",
        "owner": "Walid Al-Shami (Owner)",
        "why_need_website": "Iconic London store for roasted nuts & dates. Missing out on nationwide UK e-commerce orders.",
        "quality": "High"
    },
    {
        "id": 42,
        "business_name": "Al-Medina Dates & Dry Fruits",
        "country": "UK",
        "city": "Birmingham",
        "maps_profile": "https://maps.google.com/?q=Al+Medina+Dates+Birmingham+UK",
        "website_status": "Outdated basic page (No online ordering)",
        "social": "FB: AlMedinaDatesBham",
        "contact": "+44 121 773 9922 | almedinadatesbham@gmail.com",
        "owner": "Farhan Malik (Manager)",
        "why_need_website": "Major distributor of Ajwa & Safawi dates on Ladypool Road. Needs turnkey e-commerce store.",
        "quality": "High"
    },
    {
        "id": 43,
        "business_name": "Manchester Nut & Seed Emporium",
        "country": "UK",
        "city": "Manchester",
        "maps_profile": "https://maps.google.com/?q=Manchester+Nut+Seed+Manchester+UK",
        "website_status": "No website (Google Business Profile)",
        "social": "IG: @mcr_nut_emporium",
        "contact": "+44 161 224 5511 | mcrnutemporium@gmail.com",
        "owner": "Tariq Mahmood (Owner)",
        "why_need_website": "Rusholme area favorite for fresh cashews, almonds & pistachios. No web store.",
        "quality": "High"
    },
    {
        "id": 44,
        "business_name": "Palmyra Dates & Gourmet Gifts",
        "country": "UK",
        "city": "Leicester",
        "maps_profile": "https://maps.google.com/?q=Palmyra+Dates+Leicester+UK",
        "website_status": "Expired e-commerce platform link",
        "social": "IG: @palmyradates_uk",
        "contact": "+44 116 251 3344 | palmyradatesuk@gmail.com",
        "owner": "Zaid Al-Mansoor (Founder)",
        "why_need_website": "Specializes in luxury date gift boxes for corporate clients. E-commerce site went down.",
        "quality": "High"
    },
    {
        "id": 45,
        "business_name": "Kashmir Dry Fruits & Nuts House",
        "country": "UK",
        "city": "Bradford",
        "maps_profile": "https://maps.google.com/?q=Kashmir+Dry+Fruits+Bradford+UK",
        "website_status": "No website (WhatsApp ordering catalog)",
        "social": "FB: KashmirDryFruitsBradford",
        "contact": "+44 1274 395588 | kashmirdryfruits@gmail.com",
        "owner": "Rashid Khan (Owner)",
        "why_need_website": "Imports pine nuts, walnuts & dried figs. Taking orders manually over WhatsApp.",
        "quality": "High"
    },
    {
        "id": 46,
        "business_name": "Green Orchard Dried Fruit Co.",
        "country": "UK",
        "city": "Bristol",
        "maps_profile": "https://maps.google.com/?q=Green+Orchard+Dried+Fruit+Bristol+UK",
        "website_status": "Outdated blog-style site",
        "social": "IG: @greenorchard_bristol",
        "contact": "+44 117 924 8833 | greenorchardbristol@gmail.com",
        "owner": "Oliver Smith (Co-Owner)",
        "why_need_website": "Organic dried apple rings, mangoes & nuts. Blog has no functional cart or stock tracker.",
        "quality": "Medium"
    },
    {
        "id": 47,
        "business_name": "Al-Andalus Dates & Roastery",
        "country": "UK",
        "city": "Shepherds Bush, London",
        "maps_profile": "https://maps.google.com/?q=Al+Andalus+Dates+London+UK",
        "website_status": "No website (Google Maps listing)",
        "social": "IG: @alandalus_london",
        "contact": "+44 20 8740 1199 | alandaluslondon@gmail.com",
        "owner": "Youssef Al-Andalusi (Owner)",
        "why_need_website": "Popular West London shop for Medjool dates & roasted seeds. Needs modern online checkout.",
        "quality": "High"
    },
    {
        "id": 48,
        "business_name": "Highland Dried Fruit & Nut Merchants",
        "country": "UK",
        "city": "Glasgow, Scotland",
        "maps_profile": "https://maps.google.com/?q=Highland+Dried+Fruit+Glasgow+UK",
        "website_status": "No website (FB business page only)",
        "social": "FB: HighlandFruitMerchants",
        "contact": "+44 141 423 6677 | highlandfruitglasgow@gmail.com",
        "owner": "Callum McGregor (Co-Owner)",
        "why_need_website": "Gourmet snack mixes & trail foods. Lacks online web store for Scottish orders.",
        "quality": "Medium"
    },
    {
        "id": 49,
        "business_name": "Sultan Food & Dry Fruit Bazaar",
        "country": "UK",
        "city": "Leeds",
        "maps_profile": "https://maps.google.com/?q=Sultan+Dry+Fruit+Bazaar+Leeds+UK",
        "website_status": "Outdated site with broken payment button",
        "social": "FB: SultanBazaarLeeds",
        "contact": "+44 113 248 9911 | sultanbazaarleeds@gmail.com",
        "owner": "Asif Sultan (Owner)",
        "why_need_website": "High volume offline store. Payment gateway on site broken for 6+ months.",
        "quality": "High"
    },
    {
        "id": 50,
        "business_name": "Bactrian Nut & Date Importers",
        "country": "UK",
        "city": "Southall, London",
        "maps_profile": "https://maps.google.com/?q=Bactrian+Nut+Importers+Southall+London",
        "website_status": "No website (Phone/WhatsApp orders)",
        "social": "IG: @bactriannuts_london",
        "contact": "+44 20 8574 3322 | bactriannuts@outlook.com",
        "owner": "Hamid Rahimi (Manager)",
        "why_need_website": "B2B and retail seller of Afghan dates, almonds & pistachios in Southall.",
        "quality": "High"
    },
    {
        "id": 51,
        "business_name": "East End Nut Roasteries",
        "country": "UK",
        "city": "Whitechapel, London",
        "maps_profile": "https://maps.google.com/?q=East+End+Nut+Roasteries+Whitechapel+London",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: EastEndNutRoasteries",
        "contact": "+44 20 7247 8844 | eastendnuts@gmail.com",
        "owner": "Ali Ahmed (Owner)",
        "why_need_website": "Fresh roaster of cashews, macadamias & hazelnuts. Missing out on East London delivery app alternative.",
        "quality": "High"
    },
    {
        "id": 52,
        "business_name": "Caspian Dry Fruit & Gourmet Snacks",
        "country": "UK",
        "city": "Nottingham",
        "maps_profile": "https://maps.google.com/?q=Caspian+Dry+Fruit+Nottingham+UK",
        "website_status": "Outdated WIX site",
        "social": "IG: @caspian_snacks_nott",
        "contact": "+44 115 950 2277 | caspiansnacks@gmail.com",
        "owner": "Reza Ghasemi (Owner)",
        "why_need_website": "Specializes in Persian dried figs, barberries & saffron-coated pistachios. WIX site lacks polish.",
        "quality": "High"
    },
    {
        "id": 53,
        "business_name": "Royal Palm Date Boutique",
        "country": "UK",
        "city": "Kensington, London",
        "maps_profile": "https://maps.google.com/?q=Royal+Palm+Date+Boutique+London",
        "website_status": "No e-commerce (Brochure site only)",
        "social": "IG: @royalpalmdates_uk",
        "contact": "+44 20 7937 6622 | concierge@royalpalmdates.co.uk",
        "owner": "Noura Al-Sabah (Director)",
        "why_need_website": "Luxury date brand targeting high net worth clients in London. Needs premium Next.js storefront.",
        "quality": "High"
    },
    {
        "id": 54,
        "business_name": "Yorkshire Organic Nut House",
        "country": "UK",
        "city": "Sheffield",
        "maps_profile": "https://maps.google.com/?q=Yorkshire+Organic+Nut+Sheffield+UK",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: YorkshireNutHouse",
        "contact": "+44 114 272 1100 | yorkshirenuthouse@gmail.com",
        "owner": "David Clarke (Owner)",
        "why_need_website": "Sells organic raw & roasted nuts in bulk bins offline. Needs e-commerce storefront.",
        "quality": "Medium"
    },
    {
        "id": 55,
        "business_name": "Silk Road Dry Fruits & Spices",
        "country": "UK",
        "city": "Cardiff, Wales",
        "maps_profile": "https://maps.google.com/?q=Silk+Road+Dry+Fruits+Cardiff+UK",
        "website_status": "No website (Instagram DM sales)",
        "social": "IG: @silkroad_cardiff",
        "contact": "+44 29 2034 5588 | silkroadcardiff@gmail.com",
        "owner": "Kawa Rashid (Owner)",
        "why_need_website": "Unique dried fruits & nuts in Cardiff city center. Currently managing orders via DMs.",
        "quality": "High"
    },
    {
        "id": 56,
        "business_name": "Al-Karam Sweets & Date Merchants",
        "country": "UK",
        "city": "Luton",
        "maps_profile": "https://maps.google.com/?q=Al+Karam+Date+Merchants+Luton+UK",
        "website_status": "Outdated page with non-working shopping cart",
        "social": "FB: AlKaramLuton",
        "contact": "+44 1582 481199 | alkaramluton@gmail.com",
        "owner": "Mohammed Karam (Manager)",
        "why_need_website": "Major dates supplier in Bedfordshire. Existing site shopping cart is completely broken.",
        "quality": "High"
    },
    {
        "id": 57,
        "business_name": "Solent Dried Fruit & Nut Wholesalers",
        "country": "UK",
        "city": "Southampton",
        "maps_profile": "https://maps.google.com/?q=Solent+Dried+Fruit+Southampton+UK",
        "website_status": "No e-commerce (PDF product list only)",
        "social": "FB: SolentDriedFruit",
        "contact": "+44 23 8022 4411 | sales@solentdriedfruit.co.uk",
        "owner": "Arthur Pendelton (Director)",
        "why_need_website": "Wants to launch direct-to-consumer online nut brand alongside wholesale operation.",
        "quality": "Medium"
    },
    {
        "id": 58,
        "business_name": "Apex Date & Snack Emporium",
        "country": "UK",
        "city": "Slough",
        "maps_profile": "https://maps.google.com/?q=Apex+Date+Emporium+Slough+UK",
        "website_status": "No website (Google Maps profile)",
        "social": "IG: @apex_dates_slough",
        "contact": "+44 1753 538800 | apexdates@gmail.com",
        "owner": "Sukhwinder Singh (Owner)",
        "why_need_website": "High volume retail shop for almonds, dates, and trail mixes in Slough.",
        "quality": "High"
    },
    {
        "id": 59,
        "business_name": "Atlas Mountains Date Co.",
        "country": "UK",
        "city": "Croydon, London",
        "maps_profile": "https://maps.google.com/?q=Atlas+Mountains+Date+Croydon+London",
        "website_status": "No website (FB page only)",
        "social": "FB: AtlasMountainsDates",
        "contact": "+44 20 8688 3355 | atlasdatesuk@gmail.com",
        "owner": "Hicham El-Mansi (Owner)",
        "why_need_website": "Imports Deglet Noor dates & Moroccan almonds. Lacks automated online checkout.",
        "quality": "High"
    },
    {
        "id": 60,
        "business_name": "Midlands Gourmet Nut Roasters",
        "country": "UK",
        "city": "Coventry",
        "maps_profile": "https://maps.google.com/?q=Midlands+Gourmet+Nut+Coventry+UK",
        "website_status": "Outdated site without mobile support",
        "social": "IG: @midlandsnutroasters",
        "contact": "+44 24 7622 9944 | info@midlandsnutroasters.co.uk",
        "owner": "Paul Edwards (Founder)",
        "why_need_website": "Roasts artisan flavored nuts. Current website built in 2014 is unreadable on smartphones.",
        "quality": "High"
    },

    # --- AUSTRALIA LEADS (61 - 72) ---
    {
        "id": 61,
        "business_name": "Al-Mina Dates & Nut Roastery",
        "country": "Australia",
        "city": "Lakemba, Sydney, NSW",
        "maps_profile": "https://maps.google.com/?q=Al+Mina+Dates+Lakemba+Sydney",
        "website_status": "No website (Google Maps & Facebook page)",
        "social": "FB: AlMinaDatesLakemba / IG: @alminadates_sydney",
        "contact": "+61 2 9750 8822 | alminadates@gmail.com",
        "owner": "Bilal Al-Mina (Owner)",
        "why_need_website": "Very famous Sydney store for imported dates & roasted nuts. Lacks e-commerce store for interstate delivery.",
        "quality": "High"
    },
    {
        "id": 62,
        "business_name": "Sydney Nut & Dry Fruit Market",
        "country": "Australia",
        "city": "Auburn, Sydney, NSW",
        "maps_profile": "https://maps.google.com/?q=Sydney+Nut+Dry+Fruit+Auburn+NSW",
        "website_status": "No website (Google Maps Profile)",
        "social": "FB: SydneyNutMarketAuburn",
        "contact": "+61 2 9649 3377 | sydneynutmarket@gmail.com",
        "owner": "Jihad El-Hussein (Manager)",
        "why_need_website": "High volume retail shop in Auburn selling bulk nuts & dates. Needs digital storefront.",
        "quality": "High"
    },
    {
        "id": 63,
        "business_name": "Melbourne Date & Gourmet Nut House",
        "country": "Australia",
        "city": "Coburg, Melbourne, VIC",
        "maps_profile": "https://maps.google.com/?q=Melbourne+Date+Nut+House+Coburg+VIC",
        "website_status": "Outdated WIX free store with broken checkout",
        "social": "IG: @melbourne_date_house",
        "contact": "+61 3 9354 2266 | melbournedatehouse@gmail.com",
        "owner": "Tarek Mansour (Owner)",
        "why_need_website": "Popular Coburg store. Free WIX store has checkout issues causing lost online sales.",
        "quality": "High"
    },
    {
        "id": 64,
        "business_name": "Sunraysia Dried Fruit Merchants",
        "country": "Australia",
        "city": "Mildura, VIC",
        "maps_profile": "https://maps.google.com/?q=Sunraysia+Dried+Fruit+Mildura+VIC",
        "website_status": "Outdated legacy site (No online cart)",
        "social": "FB: SunraysiaDriedFruits",
        "contact": "+61 3 5023 1188 | sales@sunraysiadriedfruit.com.au",
        "owner": "Greg Henderson (Director)",
        "why_need_website": "Direct grower of Australian sultanas & dried apricots. Site is purely informative without cart.",
        "quality": "High"
    },
    {
        "id": 65,
        "business_name": "Queensland Macadamia & Nut Cottage",
        "country": "Australia",
        "city": "Brisbane, QLD",
        "maps_profile": "https://maps.google.com/?q=Queensland+Macadamia+Nut+Cottage+Brisbane",
        "website_status": "No website (Instagram store bio link empty)",
        "social": "IG: @qld_macadamia_cottage",
        "contact": "+61 7 3217 9900 | qldmacadamia@gmail.com",
        "owner": "Fiona Campbell (Owner)",
        "why_need_website": "Artisanal honey-roasted macadamias & local pecans. Takes order via IG DMs manually.",
        "quality": "High"
    },
    {
        "id": 66,
        "business_name": "Al-Barakah Dates & Organic Foods",
        "country": "Australia",
        "city": "Perth, WA",
        "maps_profile": "https://maps.google.com/?q=Al+Barakah+Dates+Perth+WA",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: AlBarakahDatesPerth",
        "contact": "+61 8 9470 5544 | albarakahperth@gmail.com",
        "owner": "Rashid Al-Kindi (Owner)",
        "why_need_website": "Only specialty date store in Southern Perth. Wants automated web checkout.",
        "quality": "High"
    },
    {
        "id": 67,
        "business_name": "Perth Nut Roasters & Dried Fruit",
        "country": "Australia",
        "city": "Morley, Perth, WA",
        "maps_profile": "https://maps.google.com/?q=Perth+Nut+Roasters+Morley+WA",
        "website_status": "Basic static HTML page",
        "social": "IG: @perth_nut_roasters",
        "contact": "+61 8 9276 3311 | perthnutroasters@gmail.com",
        "owner": "Tony Rossi (Co-Founder)",
        "why_need_website": "Fresh roaster of almonds, cashews & trail mixes. Modern design & cart needed.",
        "quality": "High"
    },
    {
        "id": 68,
        "business_name": "Adelaide Organic Dried Fruit & Nuts",
        "country": "Australia",
        "city": "Adelaide, SA",
        "maps_profile": "https://maps.google.com/?q=Adelaide+Organic+Dried+Fruit+Adelaide+SA",
        "website_status": "No website (FB business profile)",
        "social": "FB: AdelaideOrganicDriedFruits",
        "contact": "+61 8 8231 6622 | adelaidedriedfruits@gmail.com",
        "owner": "Sarah Jenkins (Owner)",
        "why_need_website": "Sells organic dried apples, figs & almonds at Adelaide Central Market. Needs web shop.",
        "quality": "Medium"
    },
    {
        "id": 69,
        "business_name": "Sahara Date Emporium",
        "country": "Australia",
        "city": "Bankstown, Sydney, NSW",
        "maps_profile": "https://maps.google.com/?q=Sahara+Date+Emporium+Bankstown+NSW",
        "website_status": "No website (WhatsApp order catalog)",
        "social": "IG: @saharadates_bankstown",
        "contact": "+61 2 9709 4433 | saharadatesaus@gmail.com",
        "owner": "Mo Al-Dabbagh (Owner)",
        "why_need_website": "High foot traffic store for luxury date boxes. Orders processed manually via WhatsApp.",
        "quality": "High"
    },
    {
        "id": 70,
        "business_name": "Yarra Valley Dried Fruit & Snack Barn",
        "country": "Australia",
        "city": "Yarra Glen, VIC",
        "maps_profile": "https://maps.google.com/?q=Yarra+Valley+Dried+Fruit+Yarra+Glen+VIC",
        "website_status": "Outdated WordPress site with expired SSL",
        "social": "FB: YarraValleyDriedFruit",
        "contact": "+61 3 9730 1155 | info@yarravalleydriedfruit.com.au",
        "owner": "Markus Weber (Owner)",
        "why_need_website": "Tourist venue in Yarra Valley. Expired SSL displays security warning to potential shoppers.",
        "quality": "High"
    },
    {
        "id": 71,
        "business_name": "Crown Dates & Nut Traders",
        "country": "Australia",
        "city": "Dandenong, VIC",
        "maps_profile": "https://maps.google.com/?q=Crown+Dates+Dandenong+VIC",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: CrownDatesDandenong",
        "contact": "+61 3 9791 8844 | crowndatesdandenong@gmail.com",
        "owner": "Hassan Crown (Manager)",
        "why_need_website": "Specialist importer of Saudi & Emirati dates. Lacks automated e-commerce storefront.",
        "quality": "High"
    },
    {
        "id": 72,
        "business_name": "Gold Coast Nut & Gourmet Snack Bar",
        "country": "Australia",
        "city": "Surfers Paradise, QLD",
        "maps_profile": "https://maps.google.com/?q=Gold+Coast+Nut+Bar+Surfers+Paradise",
        "website_status": "No website (Instagram store page)",
        "social": "IG: @gc_nutbar",
        "contact": "+61 7 5538 9911 | gcnutbar@gmail.com",
        "owner": "Liam O'Connor (Owner)",
        "why_need_website": "High foot traffic snack bar in tourist hub. Needs web store for tourist re-orders.",
        "quality": "Medium"
    },

    # --- UAE LEADS (73 - 86) ---
    {
        "id": 73,
        "business_name": "Al-Yathrib Premium Dates & Nuts",
        "country": "UAE",
        "city": "Deira, Dubai",
        "maps_profile": "https://maps.google.com/?q=Al+Yathrib+Dates+Deira+Dubai",
        "website_status": "No e-commerce site (Google Business Profile & IG)",
        "social": "IG: @yathrib_dates_dubai",
        "contact": "+971 4 226 8844 | sales@yathribuae.ae",
        "owner": "Ahmed Al-Yathribi (Managing Director)",
        "why_need_website": "Major shop in Deira Spice Souk selling dates & nuts. Processes all online requests via WhatsApp manually.",
        "quality": "High"
    },
    {
        "id": 74,
        "business_name": "Cool Dates Trading Establishment",
        "country": "UAE",
        "city": "Madinat Zayed, Abu Dhabi",
        "maps_profile": "https://maps.google.com/?q=Cool+Dates+Trading+Abu+Dhabi",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: CoolDatesAbuDhabi",
        "contact": "+971 2 633 5522 | cooldatesad@gmail.com",
        "owner": "Sultan Al-Mansoori (Owner)",
        "why_need_website": "Prime location on Al Sababah Street. Lacks online date gift box ordering portal.",
        "quality": "High"
    },
    {
        "id": 75,
        "business_name": "Walnuts General Trading L.L.C",
        "country": "UAE",
        "city": "Al Ras, Dubai",
        "maps_profile": "https://maps.google.com/?q=Walnuts+General+Trading+Al+Ras+Dubai",
        "website_status": "Static 1-page catalog without cart",
        "social": "IG: @walnutsgt_dubai",
        "contact": "+971 4 225 1199 | info@walnutsgt.ae",
        "owner": "Mohamed Saif (Operations Lead)",
        "why_need_website": "Large supplier of almonds, pistachios & dried figs in Al Ras market. Needs full e-commerce system.",
        "quality": "High"
    },
    {
        "id": 76,
        "business_name": "Choco World Dates & Nuts",
        "country": "UAE",
        "city": "Mussafah, Abu Dhabi",
        "maps_profile": "https://maps.google.com/?q=Choco+World+Dates+Nuts+Mussafah",
        "website_status": "No website (FB & Instagram only)",
        "social": "FB: ChocoWorldAbuDhabi / IG: @chocoworld_ae",
        "contact": "+971 2 555 7733 | chocoworldae@gmail.com",
        "owner": "Faisal Al-Tamimi (Owner)",
        "why_need_website": "Specializes in chocolate-covered stuffed dates & luxury nuts. Takes orders via Instagram DMs.",
        "quality": "High"
    },
    {
        "id": 77,
        "business_name": "Safa Dry Fruits & Spices",
        "country": "UAE",
        "city": "Sharjah",
        "maps_profile": "https://maps.google.com/?q=Safa+Dry+Fruits+Sharjah",
        "website_status": "No website (Google Business Profile)",
        "social": "FB: SafaDryFruitsSharjah",
        "contact": "+971 6 568 4411 | safadryfruitsshj@gmail.com",
        "owner": "Nasir Khan (Store Manager)",
        "why_need_website": "Busy retail shop in Sharjah selling premium dates & imported roasted seeds.",
        "quality": "High"
    },
    {
        "id": 78,
        "business_name": "Emirates Palm Dates & Sweets",
        "country": "UAE",
        "city": "Al Ain",
        "maps_profile": "https://maps.google.com/?q=Emirates+Palm+Dates+Al+Ain",
        "website_status": "Outdated flash-era site",
        "social": "IG: @emiratespalmdates_alain",
        "contact": "+971 3 766 2288 | emiratespalmalain@gmail.com",
        "owner": "Rashid Al-Dhaheri (Owner)",
        "why_need_website": "Al Ain local farm store. Web design is broken on mobile screens, losing UAE holiday orders.",
        "quality": "High"
    },
    {
        "id": 79,
        "business_name": "Al-Qasr Nut Roastery & Roasters",
        "country": "UAE",
        "city": "Al Qusais, Dubai",
        "maps_profile": "https://maps.google.com/?q=Al+Qasr+Nut+Roastery+Al+Qusais+Dubai",
        "website_status": "No website (WhatsApp business catalog)",
        "social": "IG: @alqasr_roastery_dxb",
        "contact": "+971 4 263 9955 | alqasrroastery@gmail.com",
        "owner": "Hamdan Al-Nuaimi (Owner)",
        "why_need_website": "Roasts daily cashew, hazelnut & macadamia mixes. Needs direct customer online checkout.",
        "quality": "High"
    },
    {
        "id": 80,
        "business_name": "Royal Crown Dates & Dried Fruit",
        "country": "UAE",
        "city": "Fujairah",
        "maps_profile": "https://maps.google.com/?q=Royal+Crown+Dates+Fujairah",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: RoyalCrownFujairah",
        "contact": "+971 9 222 7700 | royalcrownfuj@gmail.com",
        "owner": "Saeed Al-Kabi (Owner)",
        "why_need_website": "Popular tourist stop for local dried fruits & organic dates in Fujairah.",
        "quality": "Medium"
    },
    {
        "id": 81,
        "business_name": "Golden Oasis Dates Trading",
        "country": "UAE",
        "city": "Ras Al Khaimah",
        "maps_profile": "https://maps.google.com/?q=Golden+Oasis+Dates+RAK",
        "website_status": "Outdated 1-page HTML site",
        "social": "IG: @goldenoasis_rak",
        "contact": "+971 7 233 4411 | goldenoasisrak@gmail.com",
        "owner": "Khalid Al-Shehhi (Owner)",
        "why_need_website": "Local RAK dates farm shop. Outdated HTML site has no e-commerce backend.",
        "quality": "High"
    },
    {
        "id": 82,
        "business_name": "Al-Diwan Date Boutique",
        "country": "UAE",
        "city": "Downtown Dubai",
        "maps_profile": "https://maps.google.com/?q=Al+Diwan+Date+Boutique+Dubai",
        "website_status": "No e-commerce site (Instagram orders only)",
        "social": "IG: @aldiwan_dates_dubai",
        "contact": "+971 4 456 1122 | concierge@aldiwandates.ae",
        "owner": "Sheikha Al-Maktoum (Brand Manager)",
        "why_need_website": "High-end luxury date gift box store. Selling exclusively via Instagram DMs, needs luxury web storefront.",
        "quality": "High"
    },
    {
        "id": 83,
        "business_name": "Al-Zaeem Roastery & Dry Fruits",
        "country": "UAE",
        "city": "Ajman",
        "maps_profile": "https://maps.google.com/?q=Al+Zaeem+Roastery+Ajman",
        "website_status": "No website (Google Maps Profile)",
        "social": "FB: AlZaeemRoasteryAjman",
        "contact": "+971 6 744 3388 | alzaeemajman@gmail.com",
        "owner": "Zaeem Al-Hashimi (Owner)",
        "why_need_website": "Fresh roaster of Lebanese style nuts & seeds in Ajman.",
        "quality": "Medium"
    },
    {
        "id": 84,
        "business_name": "Pearl of the Desert Dates",
        "country": "UAE",
        "city": "Sharjah City Center",
        "maps_profile": "https://maps.google.com/?q=Pearl+of+the+Desert+Dates+Sharjah",
        "website_status": "Outdated WIX site (Broken SSL)",
        "social": "IG: @pearldesertdates_shj",
        "contact": "+971 6 539 8811 | pearldesertdates@gmail.com",
        "owner": "Marwan Al-Zarooni (Owner)",
        "why_need_website": "Store front selling premium Kholas & Sukkari dates. WIX site has SSL security issues.",
        "quality": "High"
    },
    {
        "id": 85,
        "business_name": "Al-Bustan Dates & Organic Nuts",
        "country": "UAE",
        "city": "Al Barsha, Dubai",
        "maps_profile": "https://maps.google.com/?q=Al+Bustan+Dates+Al+Barsha+Dubai",
        "website_status": "No website (WhatsApp order link only)",
        "social": "IG: @albustan_dates_barsha",
        "contact": "+971 4 399 2266 | albustandatesdxb@gmail.com",
        "owner": "Tariq Al-Ghurair (Manager)",
        "why_need_website": "Located in Al Barsha near Mall of Emirates. Needs instant e-commerce store for hotel & resident delivery.",
        "quality": "High"
    },
    {
        "id": 86,
        "business_name": "Bait Al-Tamoorm Dates Store",
        "country": "UAE",
        "city": "Al Karama, Dubai",
        "maps_profile": "https://maps.google.com/?q=Bait+Al+Tamoorm+Karama+Dubai",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: BaitAlTamoormKarama",
        "contact": "+971 4 337 5599 | baitaltamoorm@gmail.com",
        "owner": "Rashid Al-Falasi (Owner)",
        "why_need_website": "Popular Karama neighborhood date & nut store. Relying purely on walk-in traffic.",
        "quality": "High"
    },

    # --- SAUDI ARABIA LEADS (87 - 94) ---
    {
        "id": 87,
        "business_name": "Khair Al-Nakhil Organic Dates",
        "country": "Saudi Arabia",
        "city": "Madinah",
        "maps_profile": "https://maps.google.com/?q=Khair+Al+Nakhil+Madinah+Saudi",
        "website_status": "No website (WhatsApp order catalog & IG)",
        "social": "IG: @khair_alnakhil_madinah",
        "contact": "+966 54 246 0828 | khairnakhil@gmail.com",
        "owner": "Sheikh Abdulrahman Al-Madani (Owner)",
        "why_need_website": "Famous date farm store near Madinah Haram. Takes hundreds of international pilgrim orders via WhatsApp manually.",
        "quality": "High"
    },
    {
        "id": 88,
        "business_name": "Sulemaniyah Gourmet Date & Nut Market",
        "country": "Saudi Arabia",
        "city": "Sulemaniyah, Riyadh",
        "maps_profile": "https://maps.google.com/?q=Sulemaniyah+Date+Nut+Market+Riyadh",
        "website_status": "No website (Google Business Profile)",
        "social": "IG: @sulemaniyah_dates_riyadh",
        "contact": "+966 11 465 8822 | sulemaniyahdates@gmail.com",
        "owner": "Fahad Al-Subaie (Managing Director)",
        "why_need_website": "Top destination in Riyadh for Sukkari dates & premium roasted nuts. No online shop.",
        "quality": "High"
    },
    {
        "id": 89,
        "business_name": "Al-Balad Heritage Date & Spice Store",
        "country": "Saudi Arabia",
        "city": "Al-Balad, Jeddah",
        "maps_profile": "https://maps.google.com/?q=Al+Balad+Date+Store+Jeddah",
        "website_status": "Outdated static catalog site",
        "social": "FB: AlBaladDatesJeddah",
        "contact": "+966 12 647 3311 | baladdatesjeddah@gmail.com",
        "owner": "Yasser Al-Ghamdi (Owner)",
        "why_need_website": "Historic shop in Jeddah Al-Balad. Site has no e-commerce engine or cart system.",
        "quality": "High"
    },
    {
        "id": 90,
        "business_name": "Al-Nakhla Al-Zahabiya Dates",
        "country": "Saudi Arabia",
        "city": "Al Qassim / Buraidah",
        "maps_profile": "https://maps.google.com/?q=Al+Nakhla+Al+Zahabiya+Buraidah",
        "website_status": "No website (Instagram store page)",
        "social": "IG: @nakhla_zahabiya_qassim",
        "contact": "+966 50 514 9988 | nakhlazahabiya@gmail.com",
        "owner": "Saleh Al-Tuwaijri (Owner)",
        "why_need_website": "Direct date producer in Qassim (Date capital of Saudi). Sells via IG DMs, needs proper e-commerce.",
        "quality": "High"
    },
    {
        "id": 91,
        "business_name": "Al-Ahsa Palm Dates & Sweets",
        "country": "Saudi Arabia",
        "city": "Al-Ahsa",
        "maps_profile": "https://maps.google.com/?q=Al+Ahsa+Palm+Dates+Saudi",
        "website_status": "Outdated site with broken order form",
        "social": "FB: AlAhsaDatesSaudi",
        "contact": "+966 13 582 4477 | alahsadates@gmail.com",
        "owner": "Abdullah Al-Khatib (Owner)",
        "why_need_website": "Famous for Khlas dates from Al-Ahsa Oasis. Order form on current site returns server errors.",
        "quality": "High"
    },
    {
        "id": 92,
        "business_name": "Royal Roastery & Nut Traders",
        "country": "Saudi Arabia",
        "city": "Dammam",
        "maps_profile": "https://maps.google.com/?q=Royal+Roastery+Dammam+Saudi",
        "website_status": "No website (Google Maps profile)",
        "social": "IG: @royal_roastery_dammam",
        "contact": "+966 13 834 5599 | royalroasterydammam@gmail.com",
        "owner": "Bandar Al-Otaibi (Owner)",
        "why_need_website": "High volume nut roaster in Eastern Province. Needs custom online ordering for corporate gifts.",
        "quality": "High"
    },
    {
        "id": 93,
        "business_name": "Quba Dates & Souvenirs Market",
        "country": "Saudi Arabia",
        "city": "Madinah",
        "maps_profile": "https://maps.google.com/?q=Quba+Dates+Market+Madinah",
        "website_status": "No website (WhatsApp order catalog)",
        "social": "FB: QubaDatesMadinah",
        "contact": "+966 56 789 2211 | qubadatesmadinah@gmail.com",
        "owner": "Ibrahim Al-Husseini (Manager)",
        "why_need_website": "Located near Quba Mosque. Huge demand from Umrah pilgrims wanting online re-orders.",
        "quality": "High"
    },
    {
        "id": 94,
        "business_name": "Al-Olaya Date & Luxury Snack Boutique",
        "country": "Saudi Arabia",
        "city": "Al-Olaya, Riyadh",
        "maps_profile": "https://maps.google.com/?q=Al+Olaya+Date+Boutique+Riyadh",
        "website_status": "No website (Instagram DM sales)",
        "social": "IG: @olaya_date_boutique",
        "contact": "+966 11 217 6633 | info@olayadates.sa",
        "owner": "Noura Al-Saud (Brand Director)",
        "why_need_website": "Luxury date shop in financial district of Riyadh. Manually managing VIP client orders via WhatsApp.",
        "quality": "High"
    },

    # --- GERMANY LEADS (95 - 100) ---
    {
        "id": 95,
        "business_name": "Dattel & Nuss Haus Berlin",
        "country": "Germany",
        "city": "Neukölln, Berlin",
        "maps_profile": "https://maps.google.com/?q=Dattel+Nuss+Haus+Berlin",
        "website_status": "No website (Google Business Profile & IG)",
        "social": "IG: @dattelnuss_berlin",
        "contact": "+49 30 6273 8844 | dattelnussberlin@gmail.com",
        "owner": "Mehmet Yilmaz (Owner)",
        "why_need_website": "Popular Berlin store for organic dates, roasted almonds & pistachios. No online shop.",
        "quality": "High"
    },
    {
        "id": 96,
        "business_name": "Frankfurt Trockenfrüchte & Nüsse",
        "country": "Germany",
        "city": "Frankfurt am Main",
        "maps_profile": "https://maps.google.com/?q=Frankfurt+Trockenfruechte+Frankfurt",
        "website_status": "Outdated German site (No SSL / No cart)",
        "social": "FB: FrankfurtTrockenfruechte",
        "contact": "+49 69 2992 4411 | info@frankfurttrockenfruechte.de",
        "owner": "Stefan Becker (Co-Owner)",
        "why_need_website": "Speciality store in Frankfurt city center. Outdated site lacks mobile checkout & SSL security.",
        "quality": "High"
    },
    {
        "id": 97,
        "business_name": "Orient Datteln & Feinkost",
        "country": "Germany",
        "city": "Munich",
        "maps_profile": "https://maps.google.com/?q=Orient+Datteln+Munich",
        "website_status": "No website (Instagram order page)",
        "social": "IG: @orientdatteln_muc",
        "contact": "+49 89 5388 9922 | orientdatteln@gmail.com",
        "owner": "Tariq Al-Mansour (Owner)",
        "why_need_website": "Gourmet Medjool dates & stuffed nut gifts in Munich. Takes order via IG DMs.",
        "quality": "High"
    },
    {
        "id": 98,
        "business_name": "Hamburg Nut & Dried Fruit Bazaar",
        "country": "Germany",
        "city": "Hamburg",
        "maps_profile": "https://maps.google.com/?q=Hamburg+Nut+Dried+Fruit+Bazaar",
        "website_status": "No website (Google Maps profile)",
        "social": "FB: HamburgNutBazaar",
        "contact": "+49 40 3252 7700 | hamburgnutbazaar@gmail.com",
        "owner": "Kamel Ben-Ali (Owner)",
        "why_need_website": "Port city trader selling bulk almonds, walnuts & figs. No e-commerce site.",
        "quality": "High"
    },
    {
        "id": 99,
        "business_name": "Cologne Orient Express Dry Fruits",
        "country": "Germany",
        "city": "Cologne (Köln)",
        "maps_profile": "https://maps.google.com/?q=Cologne+Orient+Express+Dry+Fruits",
        "website_status": "Basic PDF catalog page",
        "social": "IG: @cologne_dryfruits",
        "contact": "+49 221 257 3388 | colognefruits@gmail.com",
        "owner": "Erol Demir (Owner)",
        "why_need_website": "Serves NRW area with high quality oriental dried fruits. Needs automated web store.",
        "quality": "Medium"
    },
    {
        "id": 100,
        "business_name": "Bavarian Bio Dried Fruit & Nut Manufactory",
        "country": "Germany",
        "city": "Nuremberg",
        "maps_profile": "https://maps.google.com/?q=Bavarian+Bio+Dried+Fruit+Nuremberg",
        "website_status": "Outdated Jimdo free site",
        "social": "FB: BavarianBioDriedFruit",
        "contact": "+49 911 244 8833 | info@bavarianbiodriedfruit.de",
        "owner": "Lukas Gruber (Founder)",
        "why_need_website": "Organic local dried apples, nuts & trail mixes. Jimdo site lacks custom branding & modern cart.",
        "quality": "High"
    }
]

file_path = "/Users/sahil/Desktop/Dryfruit/LEADS_100.csv"
fieldnames = ["id", "business_name", "country", "city", "maps_profile", "website_status", "social", "contact", "owner", "why_need_website", "quality"]

os.makedirs(os.path.dirname(file_path), exist_ok=True)
with open(file_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in leads:
        writer.writerow(row)

print(f"Successfully written {len(leads)} leads to {file_path}")
